transport:
  type: "tls"
  address: "localhost:9001"
  cert_file: "internal/config/server.crt"
  key_file: "internal/config/server.key"

chat:
  max_rooms: 10
  rooms:
    - name: "general"
      policies:
        capacity: 100
        password: "password123"
        userlevel: 2
    - name: "jebacka"
      policies:
        capacity: 2
        password: "frnda"
