transport:
  - type: "tcp"
    port: 9000

  - type: "tls"
    port: 9001
    cert_file: "server.crt"
    key_file: "server.key"

chat:
  rooms:
    - name: "general"
      capacity: 100
      description: "General chat room"
      password: "password123"
    - name: "jebacka"
      capacity: 10
      description: "jebacka chat room"
      password: "password123"